package com.example.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CorrelativeUserInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public CorrelativeUserInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAuthIdIsNull() {
            addCriterion("auth_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthIdIsNotNull() {
            addCriterion("auth_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthIdEqualTo(String value) {
            addCriterion("auth_id =", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotEqualTo(String value) {
            addCriterion("auth_id <>", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdGreaterThan(String value) {
            addCriterion("auth_id >", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdGreaterThanOrEqualTo(String value) {
            addCriterion("auth_id >=", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLessThan(String value) {
            addCriterion("auth_id <", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLessThanOrEqualTo(String value) {
            addCriterion("auth_id <=", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLike(String value) {
            addCriterion("auth_id like", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotLike(String value) {
            addCriterion("auth_id not like", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdIn(List<String> values) {
            addCriterion("auth_id in", values, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotIn(List<String> values) {
            addCriterion("auth_id not in", values, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdBetween(String value1, String value2) {
            addCriterion("auth_id between", value1, value2, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotBetween(String value1, String value2) {
            addCriterion("auth_id not between", value1, value2, "authId");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andMobileTelIsNull() {
            addCriterion("mobile_tel is null");
            return (Criteria) this;
        }

        public Criteria andMobileTelIsNotNull() {
            addCriterion("mobile_tel is not null");
            return (Criteria) this;
        }

        public Criteria andMobileTelEqualTo(String value) {
            addCriterion("mobile_tel =", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelNotEqualTo(String value) {
            addCriterion("mobile_tel <>", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelGreaterThan(String value) {
            addCriterion("mobile_tel >", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_tel >=", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelLessThan(String value) {
            addCriterion("mobile_tel <", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelLessThanOrEqualTo(String value) {
            addCriterion("mobile_tel <=", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelLike(String value) {
            addCriterion("mobile_tel like", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelNotLike(String value) {
            addCriterion("mobile_tel not like", value, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelIn(List<String> values) {
            addCriterion("mobile_tel in", values, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelNotIn(List<String> values) {
            addCriterion("mobile_tel not in", values, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelBetween(String value1, String value2) {
            addCriterion("mobile_tel between", value1, value2, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andMobileTelNotBetween(String value1, String value2) {
            addCriterion("mobile_tel not between", value1, value2, "mobileTel");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIdKindIsNull() {
            addCriterion("id_kind is null");
            return (Criteria) this;
        }

        public Criteria andIdKindIsNotNull() {
            addCriterion("id_kind is not null");
            return (Criteria) this;
        }

        public Criteria andIdKindEqualTo(Integer value) {
            addCriterion("id_kind =", value, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindNotEqualTo(Integer value) {
            addCriterion("id_kind <>", value, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindGreaterThan(Integer value) {
            addCriterion("id_kind >", value, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_kind >=", value, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindLessThan(Integer value) {
            addCriterion("id_kind <", value, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindLessThanOrEqualTo(Integer value) {
            addCriterion("id_kind <=", value, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindIn(List<Integer> values) {
            addCriterion("id_kind in", values, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindNotIn(List<Integer> values) {
            addCriterion("id_kind not in", values, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindBetween(Integer value1, Integer value2) {
            addCriterion("id_kind between", value1, value2, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdKindNotBetween(Integer value1, Integer value2) {
            addCriterion("id_kind not between", value1, value2, "idKind");
            return (Criteria) this;
        }

        public Criteria andIdNoIsNull() {
            addCriterion("id_no is null");
            return (Criteria) this;
        }

        public Criteria andIdNoIsNotNull() {
            addCriterion("id_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdNoEqualTo(String value) {
            addCriterion("id_no =", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotEqualTo(String value) {
            addCriterion("id_no <>", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoGreaterThan(String value) {
            addCriterion("id_no >", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoGreaterThanOrEqualTo(String value) {
            addCriterion("id_no >=", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLessThan(String value) {
            addCriterion("id_no <", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLessThanOrEqualTo(String value) {
            addCriterion("id_no <=", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLike(String value) {
            addCriterion("id_no like", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotLike(String value) {
            addCriterion("id_no not like", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoIn(List<String> values) {
            addCriterion("id_no in", values, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotIn(List<String> values) {
            addCriterion("id_no not in", values, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoBetween(String value1, String value2) {
            addCriterion("id_no between", value1, value2, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotBetween(String value1, String value2) {
            addCriterion("id_no not between", value1, value2, "idNo");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusIsNull() {
            addCriterion("auth_user_status is null");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusIsNotNull() {
            addCriterion("auth_user_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusEqualTo(Integer value) {
            addCriterion("auth_user_status =", value, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusNotEqualTo(Integer value) {
            addCriterion("auth_user_status <>", value, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusGreaterThan(Integer value) {
            addCriterion("auth_user_status >", value, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("auth_user_status >=", value, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusLessThan(Integer value) {
            addCriterion("auth_user_status <", value, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusLessThanOrEqualTo(Integer value) {
            addCriterion("auth_user_status <=", value, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusIn(List<Integer> values) {
            addCriterion("auth_user_status in", values, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusNotIn(List<Integer> values) {
            addCriterion("auth_user_status not in", values, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusBetween(Integer value1, Integer value2) {
            addCriterion("auth_user_status between", value1, value2, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andAuthUserStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("auth_user_status not between", value1, value2, "authUserStatus");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagIsNull() {
            addCriterion("email_active_flag is null");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagIsNotNull() {
            addCriterion("email_active_flag is not null");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagEqualTo(Integer value) {
            addCriterion("email_active_flag =", value, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagNotEqualTo(Integer value) {
            addCriterion("email_active_flag <>", value, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagGreaterThan(Integer value) {
            addCriterion("email_active_flag >", value, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("email_active_flag >=", value, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagLessThan(Integer value) {
            addCriterion("email_active_flag <", value, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagLessThanOrEqualTo(Integer value) {
            addCriterion("email_active_flag <=", value, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagIn(List<Integer> values) {
            addCriterion("email_active_flag in", values, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagNotIn(List<Integer> values) {
            addCriterion("email_active_flag not in", values, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagBetween(Integer value1, Integer value2) {
            addCriterion("email_active_flag between", value1, value2, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andEmailActiveFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("email_active_flag not between", value1, value2, "emailActiveFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagIsNull() {
            addCriterion("lock_flag is null");
            return (Criteria) this;
        }

        public Criteria andLockFlagIsNotNull() {
            addCriterion("lock_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLockFlagEqualTo(Integer value) {
            addCriterion("lock_flag =", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagNotEqualTo(Integer value) {
            addCriterion("lock_flag <>", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagGreaterThan(Integer value) {
            addCriterion("lock_flag >", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("lock_flag >=", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagLessThan(Integer value) {
            addCriterion("lock_flag <", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagLessThanOrEqualTo(Integer value) {
            addCriterion("lock_flag <=", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagIn(List<Integer> values) {
            addCriterion("lock_flag in", values, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagNotIn(List<Integer> values) {
            addCriterion("lock_flag not in", values, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagBetween(Integer value1, Integer value2) {
            addCriterion("lock_flag between", value1, value2, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("lock_flag not between", value1, value2, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagIsNull() {
            addCriterion("realname_flag is null");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagIsNotNull() {
            addCriterion("realname_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagEqualTo(Integer value) {
            addCriterion("realname_flag =", value, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagNotEqualTo(Integer value) {
            addCriterion("realname_flag <>", value, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagGreaterThan(Integer value) {
            addCriterion("realname_flag >", value, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("realname_flag >=", value, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagLessThan(Integer value) {
            addCriterion("realname_flag <", value, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagLessThanOrEqualTo(Integer value) {
            addCriterion("realname_flag <=", value, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagIn(List<Integer> values) {
            addCriterion("realname_flag in", values, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagNotIn(List<Integer> values) {
            addCriterion("realname_flag not in", values, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagBetween(Integer value1, Integer value2) {
            addCriterion("realname_flag between", value1, value2, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRealnameFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("realname_flag not between", value1, value2, "realnameFlag");
            return (Criteria) this;
        }

        public Criteria andRegSourceIsNull() {
            addCriterion("reg_source is null");
            return (Criteria) this;
        }

        public Criteria andRegSourceIsNotNull() {
            addCriterion("reg_source is not null");
            return (Criteria) this;
        }

        public Criteria andRegSourceEqualTo(String value) {
            addCriterion("reg_source =", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotEqualTo(String value) {
            addCriterion("reg_source <>", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceGreaterThan(String value) {
            addCriterion("reg_source >", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceGreaterThanOrEqualTo(String value) {
            addCriterion("reg_source >=", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceLessThan(String value) {
            addCriterion("reg_source <", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceLessThanOrEqualTo(String value) {
            addCriterion("reg_source <=", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceLike(String value) {
            addCriterion("reg_source like", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotLike(String value) {
            addCriterion("reg_source not like", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceIn(List<String> values) {
            addCriterion("reg_source in", values, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotIn(List<String> values) {
            addCriterion("reg_source not in", values, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceBetween(String value1, String value2) {
            addCriterion("reg_source between", value1, value2, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotBetween(String value1, String value2) {
            addCriterion("reg_source not between", value1, value2, "regSource");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Integer value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Integer value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Integer value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Integer value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Integer value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Integer> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Integer> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Integer value1, Integer value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdIsNull() {
            addCriterion("auth_company_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdIsNotNull() {
            addCriterion("auth_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdEqualTo(String value) {
            addCriterion("auth_company_id =", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdNotEqualTo(String value) {
            addCriterion("auth_company_id <>", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdGreaterThan(String value) {
            addCriterion("auth_company_id >", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("auth_company_id >=", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdLessThan(String value) {
            addCriterion("auth_company_id <", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("auth_company_id <=", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdLike(String value) {
            addCriterion("auth_company_id like", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdNotLike(String value) {
            addCriterion("auth_company_id not like", value, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdIn(List<String> values) {
            addCriterion("auth_company_id in", values, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdNotIn(List<String> values) {
            addCriterion("auth_company_id not in", values, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdBetween(String value1, String value2) {
            addCriterion("auth_company_id between", value1, value2, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdNotBetween(String value1, String value2) {
            addCriterion("auth_company_id not between", value1, value2, "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNull() {
            addCriterion("company_type is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNotNull() {
            addCriterion("company_type is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeEqualTo(Integer value) {
            addCriterion("company_type =", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotEqualTo(Integer value) {
            addCriterion("company_type <>", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThan(Integer value) {
            addCriterion("company_type >", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_type >=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThan(Integer value) {
            addCriterion("company_type <", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThanOrEqualTo(Integer value) {
            addCriterion("company_type <=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIn(List<Integer> values) {
            addCriterion("company_type in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotIn(List<Integer> values) {
            addCriterion("company_type not in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeBetween(Integer value1, Integer value2) {
            addCriterion("company_type between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("company_type not between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIsNull() {
            addCriterion("company_status is null");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIsNotNull() {
            addCriterion("company_status is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusEqualTo(Integer value) {
            addCriterion("company_status =", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotEqualTo(Integer value) {
            addCriterion("company_status <>", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusGreaterThan(Integer value) {
            addCriterion("company_status >", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_status >=", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusLessThan(Integer value) {
            addCriterion("company_status <", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("company_status <=", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIn(List<Integer> values) {
            addCriterion("company_status in", values, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotIn(List<Integer> values) {
            addCriterion("company_status not in", values, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusBetween(Integer value1, Integer value2) {
            addCriterion("company_status between", value1, value2, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("company_status not between", value1, value2, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andAuthEmailIsNull() {
            addCriterion("auth_email is null");
            return (Criteria) this;
        }

        public Criteria andAuthEmailIsNotNull() {
            addCriterion("auth_email is not null");
            return (Criteria) this;
        }

        public Criteria andAuthEmailEqualTo(String value) {
            addCriterion("auth_email =", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailNotEqualTo(String value) {
            addCriterion("auth_email <>", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailGreaterThan(String value) {
            addCriterion("auth_email >", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailGreaterThanOrEqualTo(String value) {
            addCriterion("auth_email >=", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailLessThan(String value) {
            addCriterion("auth_email <", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailLessThanOrEqualTo(String value) {
            addCriterion("auth_email <=", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailLike(String value) {
            addCriterion("auth_email like", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailNotLike(String value) {
            addCriterion("auth_email not like", value, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailIn(List<String> values) {
            addCriterion("auth_email in", values, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailNotIn(List<String> values) {
            addCriterion("auth_email not in", values, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailBetween(String value1, String value2) {
            addCriterion("auth_email between", value1, value2, "authEmail");
            return (Criteria) this;
        }

        public Criteria andAuthEmailNotBetween(String value1, String value2) {
            addCriterion("auth_email not between", value1, value2, "authEmail");
            return (Criteria) this;
        }

        public Criteria andRefereeIsNull() {
            addCriterion("referee is null");
            return (Criteria) this;
        }

        public Criteria andRefereeIsNotNull() {
            addCriterion("referee is not null");
            return (Criteria) this;
        }

        public Criteria andRefereeEqualTo(String value) {
            addCriterion("referee =", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotEqualTo(String value) {
            addCriterion("referee <>", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeGreaterThan(String value) {
            addCriterion("referee >", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeGreaterThanOrEqualTo(String value) {
            addCriterion("referee >=", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLessThan(String value) {
            addCriterion("referee <", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLessThanOrEqualTo(String value) {
            addCriterion("referee <=", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLike(String value) {
            addCriterion("referee like", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotLike(String value) {
            addCriterion("referee not like", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeIn(List<String> values) {
            addCriterion("referee in", values, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotIn(List<String> values) {
            addCriterion("referee not in", values, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeBetween(String value1, String value2) {
            addCriterion("referee between", value1, value2, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotBetween(String value1, String value2) {
            addCriterion("referee not between", value1, value2, "referee");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleIsNull() {
            addCriterion("total_management_scale is null");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleIsNotNull() {
            addCriterion("total_management_scale is not null");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleEqualTo(BigDecimal value) {
            addCriterion("total_management_scale =", value, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleNotEqualTo(BigDecimal value) {
            addCriterion("total_management_scale <>", value, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleGreaterThan(BigDecimal value) {
            addCriterion("total_management_scale >", value, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_management_scale >=", value, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleLessThan(BigDecimal value) {
            addCriterion("total_management_scale <", value, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_management_scale <=", value, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleIn(List<BigDecimal> values) {
            addCriterion("total_management_scale in", values, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleNotIn(List<BigDecimal> values) {
            addCriterion("total_management_scale not in", values, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_management_scale between", value1, value2, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andTotalManagementScaleNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_management_scale not between", value1, value2, "totalManagementScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleIsNull() {
            addCriterion("current_scale is null");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleIsNotNull() {
            addCriterion("current_scale is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleEqualTo(BigDecimal value) {
            addCriterion("current_scale =", value, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleNotEqualTo(BigDecimal value) {
            addCriterion("current_scale <>", value, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleGreaterThan(BigDecimal value) {
            addCriterion("current_scale >", value, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_scale >=", value, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleLessThan(BigDecimal value) {
            addCriterion("current_scale <", value, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_scale <=", value, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleIn(List<BigDecimal> values) {
            addCriterion("current_scale in", values, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleNotIn(List<BigDecimal> values) {
            addCriterion("current_scale not in", values, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_scale between", value1, value2, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentScaleNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_scale not between", value1, value2, "currentScale");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumIsNull() {
            addCriterion("current_accont_num is null");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumIsNotNull() {
            addCriterion("current_accont_num is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumEqualTo(String value) {
            addCriterion("current_accont_num =", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumNotEqualTo(String value) {
            addCriterion("current_accont_num <>", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumGreaterThan(String value) {
            addCriterion("current_accont_num >", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumGreaterThanOrEqualTo(String value) {
            addCriterion("current_accont_num >=", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumLessThan(String value) {
            addCriterion("current_accont_num <", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumLessThanOrEqualTo(String value) {
            addCriterion("current_accont_num <=", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumLike(String value) {
            addCriterion("current_accont_num like", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumNotLike(String value) {
            addCriterion("current_accont_num not like", value, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumIn(List<String> values) {
            addCriterion("current_accont_num in", values, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumNotIn(List<String> values) {
            addCriterion("current_accont_num not in", values, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumBetween(String value1, String value2) {
            addCriterion("current_accont_num between", value1, value2, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumNotBetween(String value1, String value2) {
            addCriterion("current_accont_num not between", value1, value2, "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andApproveDateIsNull() {
            addCriterion("approve_date is null");
            return (Criteria) this;
        }

        public Criteria andApproveDateIsNotNull() {
            addCriterion("approve_date is not null");
            return (Criteria) this;
        }

        public Criteria andApproveDateEqualTo(Date value) {
            addCriterion("approve_date =", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotEqualTo(Date value) {
            addCriterion("approve_date <>", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateGreaterThan(Date value) {
            addCriterion("approve_date >", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateGreaterThanOrEqualTo(Date value) {
            addCriterion("approve_date >=", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLessThan(Date value) {
            addCriterion("approve_date <", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLessThanOrEqualTo(Date value) {
            addCriterion("approve_date <=", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateIn(List<Date> values) {
            addCriterion("approve_date in", values, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotIn(List<Date> values) {
            addCriterion("approve_date not in", values, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateBetween(Date value1, Date value2) {
            addCriterion("approve_date between", value1, value2, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotBetween(Date value1, Date value2) {
            addCriterion("approve_date not between", value1, value2, "approveDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateIsNull() {
            addCriterion("invalid_date is null");
            return (Criteria) this;
        }

        public Criteria andInvalidDateIsNotNull() {
            addCriterion("invalid_date is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidDateEqualTo(Date value) {
            addCriterion("invalid_date =", value, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateNotEqualTo(Date value) {
            addCriterion("invalid_date <>", value, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateGreaterThan(Date value) {
            addCriterion("invalid_date >", value, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateGreaterThanOrEqualTo(Date value) {
            addCriterion("invalid_date >=", value, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateLessThan(Date value) {
            addCriterion("invalid_date <", value, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateLessThanOrEqualTo(Date value) {
            addCriterion("invalid_date <=", value, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateIn(List<Date> values) {
            addCriterion("invalid_date in", values, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateNotIn(List<Date> values) {
            addCriterion("invalid_date not in", values, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateBetween(Date value1, Date value2) {
            addCriterion("invalid_date between", value1, value2, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andInvalidDateNotBetween(Date value1, Date value2) {
            addCriterion("invalid_date not between", value1, value2, "invalidDate");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusIsNull() {
            addCriterion("verify_status is null");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusIsNotNull() {
            addCriterion("verify_status is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusEqualTo(Integer value) {
            addCriterion("verify_status =", value, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusNotEqualTo(Integer value) {
            addCriterion("verify_status <>", value, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusGreaterThan(Integer value) {
            addCriterion("verify_status >", value, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("verify_status >=", value, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusLessThan(Integer value) {
            addCriterion("verify_status <", value, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("verify_status <=", value, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusIn(List<Integer> values) {
            addCriterion("verify_status in", values, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusNotIn(List<Integer> values) {
            addCriterion("verify_status not in", values, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusBetween(Integer value1, Integer value2) {
            addCriterion("verify_status between", value1, value2, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andVerifyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("verify_status not between", value1, value2, "verifyStatus");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNull() {
            addCriterion("audit_remark is null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNotNull() {
            addCriterion("audit_remark is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkEqualTo(String value) {
            addCriterion("audit_remark =", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotEqualTo(String value) {
            addCriterion("audit_remark <>", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThan(String value) {
            addCriterion("audit_remark >", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("audit_remark >=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThan(String value) {
            addCriterion("audit_remark <", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThanOrEqualTo(String value) {
            addCriterion("audit_remark <=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLike(String value) {
            addCriterion("audit_remark like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotLike(String value) {
            addCriterion("audit_remark not like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIn(List<String> values) {
            addCriterion("audit_remark in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotIn(List<String> values) {
            addCriterion("audit_remark not in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkBetween(String value1, String value2) {
            addCriterion("audit_remark between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotBetween(String value1, String value2) {
            addCriterion("audit_remark not between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuthIdLikeInsensitive(String value) {
            addCriterion("upper(auth_id) like", value.toUpperCase(), "authId");
            return (Criteria) this;
        }

        public Criteria andLoginNameLikeInsensitive(String value) {
            addCriterion("upper(login_name) like", value.toUpperCase(), "loginName");
            return (Criteria) this;
        }

        public Criteria andRealNameLikeInsensitive(String value) {
            addCriterion("upper(real_name) like", value.toUpperCase(), "realName");
            return (Criteria) this;
        }

        public Criteria andMobileTelLikeInsensitive(String value) {
            addCriterion("upper(mobile_tel) like", value.toUpperCase(), "mobileTel");
            return (Criteria) this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("upper(email) like", value.toUpperCase(), "email");
            return (Criteria) this;
        }

        public Criteria andIdNoLikeInsensitive(String value) {
            addCriterion("upper(id_no) like", value.toUpperCase(), "idNo");
            return (Criteria) this;
        }

        public Criteria andRegSourceLikeInsensitive(String value) {
            addCriterion("upper(reg_source) like", value.toUpperCase(), "regSource");
            return (Criteria) this;
        }

        public Criteria andAuthCompanyIdLikeInsensitive(String value) {
            addCriterion("upper(auth_company_id) like", value.toUpperCase(), "authCompanyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLikeInsensitive(String value) {
            addCriterion("upper(company_id) like", value.toUpperCase(), "companyId");
            return (Criteria) this;
        }

        public Criteria andAuthEmailLikeInsensitive(String value) {
            addCriterion("upper(auth_email) like", value.toUpperCase(), "authEmail");
            return (Criteria) this;
        }

        public Criteria andRefereeLikeInsensitive(String value) {
            addCriterion("upper(referee) like", value.toUpperCase(), "referee");
            return (Criteria) this;
        }

        public Criteria andCurrentAccontNumLikeInsensitive(String value) {
            addCriterion("upper(current_accont_num) like", value.toUpperCase(), "currentAccontNum");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLikeInsensitive(String value) {
            addCriterion("upper(audit_remark) like", value.toUpperCase(), "auditRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_correlative_user_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}