package com.example.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class FundValuationSubject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.subject_id
     *
     * @mbggenerated
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.valuation_id
     *
     * @mbggenerated
     */
    private Integer valuationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.subject_code
     *
     * @mbggenerated
     */
    private String subjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.subject_name
     *
     * @mbggenerated
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.unit_cost
     *
     * @mbggenerated
     */
    private BigDecimal unitCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.cost
     *
     * @mbggenerated
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.cost_of_netvalue
     *
     * @mbggenerated
     */
    private Double costOfNetvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.market_value
     *
     * @mbggenerated
     */
    private BigDecimal marketValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.market_of_netvalue
     *
     * @mbggenerated
     */
    private Double marketOfNetvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.valuation_appreciation
     *
     * @mbggenerated
     */
    private BigDecimal valuationAppreciation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_valuation_subject.suspension_info
     *
     * @mbggenerated
     */
    private String suspensionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.subject_id
     *
     * @return the value of t_fund_valuation_subject.subject_id
     *
     * @mbggenerated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.subject_id
     *
     * @param subjectId the value for t_fund_valuation_subject.subject_id
     *
     * @mbggenerated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.valuation_id
     *
     * @return the value of t_fund_valuation_subject.valuation_id
     *
     * @mbggenerated
     */
    public Integer getValuationId() {
        return valuationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.valuation_id
     *
     * @param valuationId the value for t_fund_valuation_subject.valuation_id
     *
     * @mbggenerated
     */
    public void setValuationId(Integer valuationId) {
        this.valuationId = valuationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.subject_code
     *
     * @return the value of t_fund_valuation_subject.subject_code
     *
     * @mbggenerated
     */
    public String getSubjectCode() {
        return subjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.subject_code
     *
     * @param subjectCode the value for t_fund_valuation_subject.subject_code
     *
     * @mbggenerated
     */
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode == null ? null : subjectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.subject_name
     *
     * @return the value of t_fund_valuation_subject.subject_name
     *
     * @mbggenerated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.subject_name
     *
     * @param subjectName the value for t_fund_valuation_subject.subject_name
     *
     * @mbggenerated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.quantity
     *
     * @return the value of t_fund_valuation_subject.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.quantity
     *
     * @param quantity the value for t_fund_valuation_subject.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.unit_cost
     *
     * @return the value of t_fund_valuation_subject.unit_cost
     *
     * @mbggenerated
     */
    public BigDecimal getUnitCost() {
        return unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.unit_cost
     *
     * @param unitCost the value for t_fund_valuation_subject.unit_cost
     *
     * @mbggenerated
     */
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.cost
     *
     * @return the value of t_fund_valuation_subject.cost
     *
     * @mbggenerated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.cost
     *
     * @param cost the value for t_fund_valuation_subject.cost
     *
     * @mbggenerated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.cost_of_netvalue
     *
     * @return the value of t_fund_valuation_subject.cost_of_netvalue
     *
     * @mbggenerated
     */
    public Double getCostOfNetvalue() {
        return costOfNetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.cost_of_netvalue
     *
     * @param costOfNetvalue the value for t_fund_valuation_subject.cost_of_netvalue
     *
     * @mbggenerated
     */
    public void setCostOfNetvalue(Double costOfNetvalue) {
        this.costOfNetvalue = costOfNetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.market_price
     *
     * @return the value of t_fund_valuation_subject.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.market_price
     *
     * @param marketPrice the value for t_fund_valuation_subject.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.market_value
     *
     * @return the value of t_fund_valuation_subject.market_value
     *
     * @mbggenerated
     */
    public BigDecimal getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.market_value
     *
     * @param marketValue the value for t_fund_valuation_subject.market_value
     *
     * @mbggenerated
     */
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.market_of_netvalue
     *
     * @return the value of t_fund_valuation_subject.market_of_netvalue
     *
     * @mbggenerated
     */
    public Double getMarketOfNetvalue() {
        return marketOfNetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.market_of_netvalue
     *
     * @param marketOfNetvalue the value for t_fund_valuation_subject.market_of_netvalue
     *
     * @mbggenerated
     */
    public void setMarketOfNetvalue(Double marketOfNetvalue) {
        this.marketOfNetvalue = marketOfNetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.valuation_appreciation
     *
     * @return the value of t_fund_valuation_subject.valuation_appreciation
     *
     * @mbggenerated
     */
    public BigDecimal getValuationAppreciation() {
        return valuationAppreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.valuation_appreciation
     *
     * @param valuationAppreciation the value for t_fund_valuation_subject.valuation_appreciation
     *
     * @mbggenerated
     */
    public void setValuationAppreciation(BigDecimal valuationAppreciation) {
        this.valuationAppreciation = valuationAppreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_valuation_subject.suspension_info
     *
     * @return the value of t_fund_valuation_subject.suspension_info
     *
     * @mbggenerated
     */
    public String getSuspensionInfo() {
        return suspensionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_valuation_subject.suspension_info
     *
     * @param suspensionInfo the value for t_fund_valuation_subject.suspension_info
     *
     * @mbggenerated
     */
    public void setSuspensionInfo(String suspensionInfo) {
        this.suspensionInfo = suspensionInfo == null ? null : suspensionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FundValuationSubject other = (FundValuationSubject) that;
        return (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getValuationId() == null ? other.getValuationId() == null : this.getValuationId().equals(other.getValuationId()))
            && (this.getSubjectCode() == null ? other.getSubjectCode() == null : this.getSubjectCode().equals(other.getSubjectCode()))
            && (this.getSubjectName() == null ? other.getSubjectName() == null : this.getSubjectName().equals(other.getSubjectName()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getUnitCost() == null ? other.getUnitCost() == null : this.getUnitCost().equals(other.getUnitCost()))
            && (this.getCost() == null ? other.getCost() == null : this.getCost().equals(other.getCost()))
            && (this.getCostOfNetvalue() == null ? other.getCostOfNetvalue() == null : this.getCostOfNetvalue().equals(other.getCostOfNetvalue()))
            && (this.getMarketPrice() == null ? other.getMarketPrice() == null : this.getMarketPrice().equals(other.getMarketPrice()))
            && (this.getMarketValue() == null ? other.getMarketValue() == null : this.getMarketValue().equals(other.getMarketValue()))
            && (this.getMarketOfNetvalue() == null ? other.getMarketOfNetvalue() == null : this.getMarketOfNetvalue().equals(other.getMarketOfNetvalue()))
            && (this.getValuationAppreciation() == null ? other.getValuationAppreciation() == null : this.getValuationAppreciation().equals(other.getValuationAppreciation()))
            && (this.getSuspensionInfo() == null ? other.getSuspensionInfo() == null : this.getSuspensionInfo().equals(other.getSuspensionInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getValuationId() == null) ? 0 : getValuationId().hashCode());
        result = prime * result + ((getSubjectCode() == null) ? 0 : getSubjectCode().hashCode());
        result = prime * result + ((getSubjectName() == null) ? 0 : getSubjectName().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getUnitCost() == null) ? 0 : getUnitCost().hashCode());
        result = prime * result + ((getCost() == null) ? 0 : getCost().hashCode());
        result = prime * result + ((getCostOfNetvalue() == null) ? 0 : getCostOfNetvalue().hashCode());
        result = prime * result + ((getMarketPrice() == null) ? 0 : getMarketPrice().hashCode());
        result = prime * result + ((getMarketValue() == null) ? 0 : getMarketValue().hashCode());
        result = prime * result + ((getMarketOfNetvalue() == null) ? 0 : getMarketOfNetvalue().hashCode());
        result = prime * result + ((getValuationAppreciation() == null) ? 0 : getValuationAppreciation().hashCode());
        result = prime * result + ((getSuspensionInfo() == null) ? 0 : getSuspensionInfo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subjectId=").append(subjectId);
        sb.append(", valuationId=").append(valuationId);
        sb.append(", subjectCode=").append(subjectCode);
        sb.append(", subjectName=").append(subjectName);
        sb.append(", quantity=").append(quantity);
        sb.append(", unitCost=").append(unitCost);
        sb.append(", cost=").append(cost);
        sb.append(", costOfNetvalue=").append(costOfNetvalue);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", marketValue=").append(marketValue);
        sb.append(", marketOfNetvalue=").append(marketOfNetvalue);
        sb.append(", valuationAppreciation=").append(valuationAppreciation);
        sb.append(", suspensionInfo=").append(suspensionInfo);
        sb.append("]");
        return sb.toString();
    }
}