spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/wazddz?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: root
    password: 123456
    #使用druid数据源    
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    minIdle: 5
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#druid的web端访问配置参数
druid:
  web:
    #url映射，多个逗号隔开
    urlMappings: /druid/*
    #登陆用户名
    loginUsername: admin
    #登陆密码
    loginPassword: 123456
    #IP白名单，多个逗号隔开
    allow: 192.168.1.218,127.0.0.1
    #IP黑名单，多个逗号隔开 (存在共同时，deny优先于allow) : 如果满足deny的即提示:Sorry, you are not
    deny: 192.168.1.100
    # 是否能够重置数据
    resetEnable: false
#最大登陆出错次数
login:
  error:
    retryCount: 1
    
#配置日志
logging:
  config: classpath:config/logback-spring.xml
    
    
