package com.example.demo.mapper;

import com.example.demo.model.FundValuation;
import com.example.demo.model.FundValuationCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FundValuationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int countByExample(FundValuationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int deleteByExample(FundValuationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer valuationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int insert(FundValuation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int insertSelective(FundValuation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    List<FundValuation> selectByExampleWithRowbounds(FundValuationCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    List<FundValuation> selectByExample(FundValuationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    FundValuation selectByPrimaryKey(Integer valuationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundValuation record, @Param("example") FundValuationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundValuation record, @Param("example") FundValuationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundValuation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundValuation record);
}