package com.example.demo.mapper;

import com.example.demo.model.FundValuationSubject;
import com.example.demo.model.FundValuationSubjectCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FundValuationSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int countByExample(FundValuationSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int deleteByExample(FundValuationSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int insert(FundValuationSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int insertSelective(FundValuationSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    List<FundValuationSubject> selectByExampleWithRowbounds(FundValuationSubjectCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    List<FundValuationSubject> selectByExample(FundValuationSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    FundValuationSubject selectByPrimaryKey(Integer subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundValuationSubject record, @Param("example") FundValuationSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundValuationSubject record, @Param("example") FundValuationSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundValuationSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_valuation_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundValuationSubject record);
}