package com.example.demo.model.fund;

import java.io.Serializable;
import java.util.Date;

public class FileIsmBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.file_id
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.extend_name
     *
     * @mbggenerated
     */
    private String extendName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.file_size
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.alias_name
     *
     * @mbggenerated
     */
    private String aliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.file_type
     *
     * @mbggenerated
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.Thumbnail
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.creat_date
     *
     * @mbggenerated
     */
    private Date creatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_file.security_class
     *
     * @mbggenerated
     */
    private String securityClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_file
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.file_id
     *
     * @return the value of ism_file.file_id
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.file_id
     *
     * @param fileId the value for ism_file.file_id
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.file_name
     *
     * @return the value of ism_file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.file_name
     *
     * @param fileName the value for ism_file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.extend_name
     *
     * @return the value of ism_file.extend_name
     *
     * @mbggenerated
     */
    public String getExtendName() {
        return extendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.extend_name
     *
     * @param extendName the value for ism_file.extend_name
     *
     * @mbggenerated
     */
    public void setExtendName(String extendName) {
        this.extendName = extendName == null ? null : extendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.file_size
     *
     * @return the value of ism_file.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.file_size
     *
     * @param fileSize the value for ism_file.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.alias_name
     *
     * @return the value of ism_file.alias_name
     *
     * @mbggenerated
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.alias_name
     *
     * @param aliasName the value for ism_file.alias_name
     *
     * @mbggenerated
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.file_type
     *
     * @return the value of ism_file.file_type
     *
     * @mbggenerated
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.file_type
     *
     * @param fileType the value for ism_file.file_type
     *
     * @mbggenerated
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.file_path
     *
     * @return the value of ism_file.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.file_path
     *
     * @param filePath the value for ism_file.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.Thumbnail
     *
     * @return the value of ism_file.Thumbnail
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.Thumbnail
     *
     * @param thumbnail the value for ism_file.Thumbnail
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.creat_date
     *
     * @return the value of ism_file.creat_date
     *
     * @mbggenerated
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.creat_date
     *
     * @param creatDate the value for ism_file.creat_date
     *
     * @mbggenerated
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.creator
     *
     * @return the value of ism_file.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.creator
     *
     * @param creator the value for ism_file.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.modify_date
     *
     * @return the value of ism_file.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.modify_date
     *
     * @param modifyDate the value for ism_file.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.modifier
     *
     * @return the value of ism_file.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.modifier
     *
     * @param modifier the value for ism_file.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_file.security_class
     *
     * @return the value of ism_file.security_class
     *
     * @mbggenerated
     */
    public String getSecurityClass() {
        return securityClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_file.security_class
     *
     * @param securityClass the value for ism_file.security_class
     *
     * @mbggenerated
     */
    public void setSecurityClass(String securityClass) {
        this.securityClass = securityClass == null ? null : securityClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_file
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileIsmBean other = (FileIsmBean) that;
        return (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getExtendName() == null ? other.getExtendName() == null : this.getExtendName().equals(other.getExtendName()))
            && (this.getFileSize() == null ? other.getFileSize() == null : this.getFileSize().equals(other.getFileSize()))
            && (this.getAliasName() == null ? other.getAliasName() == null : this.getAliasName().equals(other.getAliasName()))
            && (this.getFileType() == null ? other.getFileType() == null : this.getFileType().equals(other.getFileType()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getThumbnail() == null ? other.getThumbnail() == null : this.getThumbnail().equals(other.getThumbnail()))
            && (this.getCreatDate() == null ? other.getCreatDate() == null : this.getCreatDate().equals(other.getCreatDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getSecurityClass() == null ? other.getSecurityClass() == null : this.getSecurityClass().equals(other.getSecurityClass()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_file
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getExtendName() == null) ? 0 : getExtendName().hashCode());
        result = prime * result + ((getFileSize() == null) ? 0 : getFileSize().hashCode());
        result = prime * result + ((getAliasName() == null) ? 0 : getAliasName().hashCode());
        result = prime * result + ((getFileType() == null) ? 0 : getFileType().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getThumbnail() == null) ? 0 : getThumbnail().hashCode());
        result = prime * result + ((getCreatDate() == null) ? 0 : getCreatDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getSecurityClass() == null) ? 0 : getSecurityClass().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_file
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileName=").append(fileName);
        sb.append(", extendName=").append(extendName);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", aliasName=").append(aliasName);
        sb.append(", fileType=").append(fileType);
        sb.append(", filePath=").append(filePath);
        sb.append(", thumbnail=").append(thumbnail);
        sb.append(", creatDate=").append(creatDate);
        sb.append(", creator=").append(creator);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", securityClass=").append(securityClass);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}