package com.example.demo.model.fund;

import java.io.Serializable;
import java.math.BigDecimal;

public class PerformanceReportYearPerformanceTempBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_year_performance_temp.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_year_performance_temp.report_id
     *
     * @mbggenerated
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_year_performance_temp.profit
     *
     * @mbggenerated
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_year_performance_temp.asset
     *
     * @mbggenerated
     */
    private Integer asset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_year_performance_temp.section_type
     *
     * @mbggenerated
     */
    private Integer sectionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_year_performance_temp.performance_type
     *
     * @mbggenerated
     */
    private Integer performanceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance_report_year_performance_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_year_performance_temp.id
     *
     * @return the value of performance_report_year_performance_temp.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_year_performance_temp.id
     *
     * @param id the value for performance_report_year_performance_temp.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_year_performance_temp.report_id
     *
     * @return the value of performance_report_year_performance_temp.report_id
     *
     * @mbggenerated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_year_performance_temp.report_id
     *
     * @param reportId the value for performance_report_year_performance_temp.report_id
     *
     * @mbggenerated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_year_performance_temp.profit
     *
     * @return the value of performance_report_year_performance_temp.profit
     *
     * @mbggenerated
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_year_performance_temp.profit
     *
     * @param profit the value for performance_report_year_performance_temp.profit
     *
     * @mbggenerated
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_year_performance_temp.asset
     *
     * @return the value of performance_report_year_performance_temp.asset
     *
     * @mbggenerated
     */
    public Integer getAsset() {
        return asset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_year_performance_temp.asset
     *
     * @param asset the value for performance_report_year_performance_temp.asset
     *
     * @mbggenerated
     */
    public void setAsset(Integer asset) {
        this.asset = asset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_year_performance_temp.section_type
     *
     * @return the value of performance_report_year_performance_temp.section_type
     *
     * @mbggenerated
     */
    public Integer getSectionType() {
        return sectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_year_performance_temp.section_type
     *
     * @param sectionType the value for performance_report_year_performance_temp.section_type
     *
     * @mbggenerated
     */
    public void setSectionType(Integer sectionType) {
        this.sectionType = sectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_year_performance_temp.performance_type
     *
     * @return the value of performance_report_year_performance_temp.performance_type
     *
     * @mbggenerated
     */
    public Integer getPerformanceType() {
        return performanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_year_performance_temp.performance_type
     *
     * @param performanceType the value for performance_report_year_performance_temp.performance_type
     *
     * @mbggenerated
     */
    public void setPerformanceType(Integer performanceType) {
        this.performanceType = performanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_year_performance_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PerformanceReportYearPerformanceTempBean other = (PerformanceReportYearPerformanceTempBean) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReportId() == null ? other.getReportId() == null : this.getReportId().equals(other.getReportId()))
            && (this.getProfit() == null ? other.getProfit() == null : this.getProfit().equals(other.getProfit()))
            && (this.getAsset() == null ? other.getAsset() == null : this.getAsset().equals(other.getAsset()))
            && (this.getSectionType() == null ? other.getSectionType() == null : this.getSectionType().equals(other.getSectionType()))
            && (this.getPerformanceType() == null ? other.getPerformanceType() == null : this.getPerformanceType().equals(other.getPerformanceType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_year_performance_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReportId() == null) ? 0 : getReportId().hashCode());
        result = prime * result + ((getProfit() == null) ? 0 : getProfit().hashCode());
        result = prime * result + ((getAsset() == null) ? 0 : getAsset().hashCode());
        result = prime * result + ((getSectionType() == null) ? 0 : getSectionType().hashCode());
        result = prime * result + ((getPerformanceType() == null) ? 0 : getPerformanceType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_year_performance_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reportId=").append(reportId);
        sb.append(", profit=").append(profit);
        sb.append(", asset=").append(asset);
        sb.append(", sectionType=").append(sectionType);
        sb.append(", performanceType=").append(performanceType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}