package com.example.demo.model.fund;

import java.io.Serializable;
import java.util.Date;

public class PerformanceReportReviseTempBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_id
     *
     * @mbggenerated
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.fund_temp_id
     *
     * @mbggenerated
     */
    private String fundTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_years
     *
     * @mbggenerated
     */
    private Integer reportYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_quarter
     *
     * @mbggenerated
     */
    private Integer reportQuarter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_name
     *
     * @mbggenerated
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_time
     *
     * @mbggenerated
     */
    private Date reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_status
     *
     * @mbggenerated
     */
    private Integer reportStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.report_month
     *
     * @mbggenerated
     */
    private Integer reportMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.last_net_time
     *
     * @mbggenerated
     */
    private Date lastNetTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.build_report_status
     *
     * @mbggenerated
     */
    private Integer buildReportStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.build_report_date
     *
     * @mbggenerated
     */
    private Date buildReportDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.build_report_path
     *
     * @mbggenerated
     */
    private String buildReportPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.build_fileid_list
     *
     * @mbggenerated
     */
    private String buildFileidList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_revise_temp.fund_net_update_range
     *
     * @mbggenerated
     */
    private Integer fundNetUpdateRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance_report_revise_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_id
     *
     * @return the value of performance_report_revise_temp.report_id
     *
     * @mbggenerated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_id
     *
     * @param reportId the value for performance_report_revise_temp.report_id
     *
     * @mbggenerated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.fund_temp_id
     *
     * @return the value of performance_report_revise_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public String getFundTempId() {
        return fundTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.fund_temp_id
     *
     * @param fundTempId the value for performance_report_revise_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public void setFundTempId(String fundTempId) {
        this.fundTempId = fundTempId == null ? null : fundTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_years
     *
     * @return the value of performance_report_revise_temp.report_years
     *
     * @mbggenerated
     */
    public Integer getReportYears() {
        return reportYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_years
     *
     * @param reportYears the value for performance_report_revise_temp.report_years
     *
     * @mbggenerated
     */
    public void setReportYears(Integer reportYears) {
        this.reportYears = reportYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_quarter
     *
     * @return the value of performance_report_revise_temp.report_quarter
     *
     * @mbggenerated
     */
    public Integer getReportQuarter() {
        return reportQuarter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_quarter
     *
     * @param reportQuarter the value for performance_report_revise_temp.report_quarter
     *
     * @mbggenerated
     */
    public void setReportQuarter(Integer reportQuarter) {
        this.reportQuarter = reportQuarter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_name
     *
     * @return the value of performance_report_revise_temp.report_name
     *
     * @mbggenerated
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_name
     *
     * @param reportName the value for performance_report_revise_temp.report_name
     *
     * @mbggenerated
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_time
     *
     * @return the value of performance_report_revise_temp.report_time
     *
     * @mbggenerated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_time
     *
     * @param reportTime the value for performance_report_revise_temp.report_time
     *
     * @mbggenerated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_status
     *
     * @return the value of performance_report_revise_temp.report_status
     *
     * @mbggenerated
     */
    public Integer getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_status
     *
     * @param reportStatus the value for performance_report_revise_temp.report_status
     *
     * @mbggenerated
     */
    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.creator
     *
     * @return the value of performance_report_revise_temp.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.creator
     *
     * @param creator the value for performance_report_revise_temp.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.modify_date
     *
     * @return the value of performance_report_revise_temp.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.modify_date
     *
     * @param modifyDate the value for performance_report_revise_temp.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.modifier
     *
     * @return the value of performance_report_revise_temp.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.modifier
     *
     * @param modifier the value for performance_report_revise_temp.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.report_month
     *
     * @return the value of performance_report_revise_temp.report_month
     *
     * @mbggenerated
     */
    public Integer getReportMonth() {
        return reportMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.report_month
     *
     * @param reportMonth the value for performance_report_revise_temp.report_month
     *
     * @mbggenerated
     */
    public void setReportMonth(Integer reportMonth) {
        this.reportMonth = reportMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.last_net_time
     *
     * @return the value of performance_report_revise_temp.last_net_time
     *
     * @mbggenerated
     */
    public Date getLastNetTime() {
        return lastNetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.last_net_time
     *
     * @param lastNetTime the value for performance_report_revise_temp.last_net_time
     *
     * @mbggenerated
     */
    public void setLastNetTime(Date lastNetTime) {
        this.lastNetTime = lastNetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.build_report_status
     *
     * @return the value of performance_report_revise_temp.build_report_status
     *
     * @mbggenerated
     */
    public Integer getBuildReportStatus() {
        return buildReportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.build_report_status
     *
     * @param buildReportStatus the value for performance_report_revise_temp.build_report_status
     *
     * @mbggenerated
     */
    public void setBuildReportStatus(Integer buildReportStatus) {
        this.buildReportStatus = buildReportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.build_report_date
     *
     * @return the value of performance_report_revise_temp.build_report_date
     *
     * @mbggenerated
     */
    public Date getBuildReportDate() {
        return buildReportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.build_report_date
     *
     * @param buildReportDate the value for performance_report_revise_temp.build_report_date
     *
     * @mbggenerated
     */
    public void setBuildReportDate(Date buildReportDate) {
        this.buildReportDate = buildReportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.build_report_path
     *
     * @return the value of performance_report_revise_temp.build_report_path
     *
     * @mbggenerated
     */
    public String getBuildReportPath() {
        return buildReportPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.build_report_path
     *
     * @param buildReportPath the value for performance_report_revise_temp.build_report_path
     *
     * @mbggenerated
     */
    public void setBuildReportPath(String buildReportPath) {
        this.buildReportPath = buildReportPath == null ? null : buildReportPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.build_fileid_list
     *
     * @return the value of performance_report_revise_temp.build_fileid_list
     *
     * @mbggenerated
     */
    public String getBuildFileidList() {
        return buildFileidList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.build_fileid_list
     *
     * @param buildFileidList the value for performance_report_revise_temp.build_fileid_list
     *
     * @mbggenerated
     */
    public void setBuildFileidList(String buildFileidList) {
        this.buildFileidList = buildFileidList == null ? null : buildFileidList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_revise_temp.fund_net_update_range
     *
     * @return the value of performance_report_revise_temp.fund_net_update_range
     *
     * @mbggenerated
     */
    public Integer getFundNetUpdateRange() {
        return fundNetUpdateRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_revise_temp.fund_net_update_range
     *
     * @param fundNetUpdateRange the value for performance_report_revise_temp.fund_net_update_range
     *
     * @mbggenerated
     */
    public void setFundNetUpdateRange(Integer fundNetUpdateRange) {
        this.fundNetUpdateRange = fundNetUpdateRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_revise_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PerformanceReportReviseTempBean other = (PerformanceReportReviseTempBean) that;
        return (this.getReportId() == null ? other.getReportId() == null : this.getReportId().equals(other.getReportId()))
            && (this.getFundTempId() == null ? other.getFundTempId() == null : this.getFundTempId().equals(other.getFundTempId()))
            && (this.getReportYears() == null ? other.getReportYears() == null : this.getReportYears().equals(other.getReportYears()))
            && (this.getReportQuarter() == null ? other.getReportQuarter() == null : this.getReportQuarter().equals(other.getReportQuarter()))
            && (this.getReportName() == null ? other.getReportName() == null : this.getReportName().equals(other.getReportName()))
            && (this.getReportTime() == null ? other.getReportTime() == null : this.getReportTime().equals(other.getReportTime()))
            && (this.getReportStatus() == null ? other.getReportStatus() == null : this.getReportStatus().equals(other.getReportStatus()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getReportMonth() == null ? other.getReportMonth() == null : this.getReportMonth().equals(other.getReportMonth()))
            && (this.getLastNetTime() == null ? other.getLastNetTime() == null : this.getLastNetTime().equals(other.getLastNetTime()))
            && (this.getBuildReportStatus() == null ? other.getBuildReportStatus() == null : this.getBuildReportStatus().equals(other.getBuildReportStatus()))
            && (this.getBuildReportDate() == null ? other.getBuildReportDate() == null : this.getBuildReportDate().equals(other.getBuildReportDate()))
            && (this.getBuildReportPath() == null ? other.getBuildReportPath() == null : this.getBuildReportPath().equals(other.getBuildReportPath()))
            && (this.getBuildFileidList() == null ? other.getBuildFileidList() == null : this.getBuildFileidList().equals(other.getBuildFileidList()))
            && (this.getFundNetUpdateRange() == null ? other.getFundNetUpdateRange() == null : this.getFundNetUpdateRange().equals(other.getFundNetUpdateRange()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_revise_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getReportId() == null) ? 0 : getReportId().hashCode());
        result = prime * result + ((getFundTempId() == null) ? 0 : getFundTempId().hashCode());
        result = prime * result + ((getReportYears() == null) ? 0 : getReportYears().hashCode());
        result = prime * result + ((getReportQuarter() == null) ? 0 : getReportQuarter().hashCode());
        result = prime * result + ((getReportName() == null) ? 0 : getReportName().hashCode());
        result = prime * result + ((getReportTime() == null) ? 0 : getReportTime().hashCode());
        result = prime * result + ((getReportStatus() == null) ? 0 : getReportStatus().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getReportMonth() == null) ? 0 : getReportMonth().hashCode());
        result = prime * result + ((getLastNetTime() == null) ? 0 : getLastNetTime().hashCode());
        result = prime * result + ((getBuildReportStatus() == null) ? 0 : getBuildReportStatus().hashCode());
        result = prime * result + ((getBuildReportDate() == null) ? 0 : getBuildReportDate().hashCode());
        result = prime * result + ((getBuildReportPath() == null) ? 0 : getBuildReportPath().hashCode());
        result = prime * result + ((getBuildFileidList() == null) ? 0 : getBuildFileidList().hashCode());
        result = prime * result + ((getFundNetUpdateRange() == null) ? 0 : getFundNetUpdateRange().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_revise_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reportId=").append(reportId);
        sb.append(", fundTempId=").append(fundTempId);
        sb.append(", reportYears=").append(reportYears);
        sb.append(", reportQuarter=").append(reportQuarter);
        sb.append(", reportName=").append(reportName);
        sb.append(", reportTime=").append(reportTime);
        sb.append(", reportStatus=").append(reportStatus);
        sb.append(", creator=").append(creator);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", reportMonth=").append(reportMonth);
        sb.append(", lastNetTime=").append(lastNetTime);
        sb.append(", buildReportStatus=").append(buildReportStatus);
        sb.append(", buildReportDate=").append(buildReportDate);
        sb.append(", buildReportPath=").append(buildReportPath);
        sb.append(", buildFileidList=").append(buildFileidList);
        sb.append(", fundNetUpdateRange=").append(fundNetUpdateRange);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}