package com.example.demo.model.fund;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PerformanceReportReturnwithdrawTempBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.report_id
     *
     * @mbggenerated
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.return_rate
     *
     * @mbggenerated
     */
    private BigDecimal returnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.weektime_span
     *
     * @mbggenerated
     */
    private Integer weektimeSpan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.recovery_time
     *
     * @mbggenerated
     */
    private Integer recoveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnwithdraw_temp.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance_report_returnwithdraw_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.id
     *
     * @return the value of performance_report_returnwithdraw_temp.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.id
     *
     * @param id the value for performance_report_returnwithdraw_temp.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.report_id
     *
     * @return the value of performance_report_returnwithdraw_temp.report_id
     *
     * @mbggenerated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.report_id
     *
     * @param reportId the value for performance_report_returnwithdraw_temp.report_id
     *
     * @mbggenerated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.return_rate
     *
     * @return the value of performance_report_returnwithdraw_temp.return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReturnRate() {
        return returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.return_rate
     *
     * @param returnRate the value for performance_report_returnwithdraw_temp.return_rate
     *
     * @mbggenerated
     */
    public void setReturnRate(BigDecimal returnRate) {
        this.returnRate = returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.weektime_span
     *
     * @return the value of performance_report_returnwithdraw_temp.weektime_span
     *
     * @mbggenerated
     */
    public Integer getWeektimeSpan() {
        return weektimeSpan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.weektime_span
     *
     * @param weektimeSpan the value for performance_report_returnwithdraw_temp.weektime_span
     *
     * @mbggenerated
     */
    public void setWeektimeSpan(Integer weektimeSpan) {
        this.weektimeSpan = weektimeSpan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.recovery_time
     *
     * @return the value of performance_report_returnwithdraw_temp.recovery_time
     *
     * @mbggenerated
     */
    public Integer getRecoveryTime() {
        return recoveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.recovery_time
     *
     * @param recoveryTime the value for performance_report_returnwithdraw_temp.recovery_time
     *
     * @mbggenerated
     */
    public void setRecoveryTime(Integer recoveryTime) {
        this.recoveryTime = recoveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.begin_time
     *
     * @return the value of performance_report_returnwithdraw_temp.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.begin_time
     *
     * @param beginTime the value for performance_report_returnwithdraw_temp.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnwithdraw_temp.end_time
     *
     * @return the value of performance_report_returnwithdraw_temp.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnwithdraw_temp.end_time
     *
     * @param endTime the value for performance_report_returnwithdraw_temp.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_returnwithdraw_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PerformanceReportReturnwithdrawTempBean other = (PerformanceReportReturnwithdrawTempBean) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReportId() == null ? other.getReportId() == null : this.getReportId().equals(other.getReportId()))
            && (this.getReturnRate() == null ? other.getReturnRate() == null : this.getReturnRate().equals(other.getReturnRate()))
            && (this.getWeektimeSpan() == null ? other.getWeektimeSpan() == null : this.getWeektimeSpan().equals(other.getWeektimeSpan()))
            && (this.getRecoveryTime() == null ? other.getRecoveryTime() == null : this.getRecoveryTime().equals(other.getRecoveryTime()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_returnwithdraw_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReportId() == null) ? 0 : getReportId().hashCode());
        result = prime * result + ((getReturnRate() == null) ? 0 : getReturnRate().hashCode());
        result = prime * result + ((getWeektimeSpan() == null) ? 0 : getWeektimeSpan().hashCode());
        result = prime * result + ((getRecoveryTime() == null) ? 0 : getRecoveryTime().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_returnwithdraw_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reportId=").append(reportId);
        sb.append(", returnRate=").append(returnRate);
        sb.append(", weektimeSpan=").append(weektimeSpan);
        sb.append(", recoveryTime=").append(recoveryTime);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}