package com.example.demo.model.fund;

import java.io.Serializable;
import java.math.BigDecimal;

public class PerformanceReportReturnprofitTempBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.report_id
     *
     * @mbggenerated
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.weektime_span
     *
     * @mbggenerated
     */
    private Integer weektimeSpan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.max_rise
     *
     * @mbggenerated
     */
    private BigDecimal maxRise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.max_fall
     *
     * @mbggenerated
     */
    private BigDecimal maxFall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.avg_range
     *
     * @mbggenerated
     */
    private BigDecimal avgRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_returnprofit_temp.lately_num
     *
     * @mbggenerated
     */
    private BigDecimal latelyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance_report_returnprofit_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.id
     *
     * @return the value of performance_report_returnprofit_temp.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.id
     *
     * @param id the value for performance_report_returnprofit_temp.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.report_id
     *
     * @return the value of performance_report_returnprofit_temp.report_id
     *
     * @mbggenerated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.report_id
     *
     * @param reportId the value for performance_report_returnprofit_temp.report_id
     *
     * @mbggenerated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.weektime_span
     *
     * @return the value of performance_report_returnprofit_temp.weektime_span
     *
     * @mbggenerated
     */
    public Integer getWeektimeSpan() {
        return weektimeSpan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.weektime_span
     *
     * @param weektimeSpan the value for performance_report_returnprofit_temp.weektime_span
     *
     * @mbggenerated
     */
    public void setWeektimeSpan(Integer weektimeSpan) {
        this.weektimeSpan = weektimeSpan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.max_rise
     *
     * @return the value of performance_report_returnprofit_temp.max_rise
     *
     * @mbggenerated
     */
    public BigDecimal getMaxRise() {
        return maxRise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.max_rise
     *
     * @param maxRise the value for performance_report_returnprofit_temp.max_rise
     *
     * @mbggenerated
     */
    public void setMaxRise(BigDecimal maxRise) {
        this.maxRise = maxRise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.max_fall
     *
     * @return the value of performance_report_returnprofit_temp.max_fall
     *
     * @mbggenerated
     */
    public BigDecimal getMaxFall() {
        return maxFall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.max_fall
     *
     * @param maxFall the value for performance_report_returnprofit_temp.max_fall
     *
     * @mbggenerated
     */
    public void setMaxFall(BigDecimal maxFall) {
        this.maxFall = maxFall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.avg_range
     *
     * @return the value of performance_report_returnprofit_temp.avg_range
     *
     * @mbggenerated
     */
    public BigDecimal getAvgRange() {
        return avgRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.avg_range
     *
     * @param avgRange the value for performance_report_returnprofit_temp.avg_range
     *
     * @mbggenerated
     */
    public void setAvgRange(BigDecimal avgRange) {
        this.avgRange = avgRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_returnprofit_temp.lately_num
     *
     * @return the value of performance_report_returnprofit_temp.lately_num
     *
     * @mbggenerated
     */
    public BigDecimal getLatelyNum() {
        return latelyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_returnprofit_temp.lately_num
     *
     * @param latelyNum the value for performance_report_returnprofit_temp.lately_num
     *
     * @mbggenerated
     */
    public void setLatelyNum(BigDecimal latelyNum) {
        this.latelyNum = latelyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_returnprofit_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PerformanceReportReturnprofitTempBean other = (PerformanceReportReturnprofitTempBean) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReportId() == null ? other.getReportId() == null : this.getReportId().equals(other.getReportId()))
            && (this.getWeektimeSpan() == null ? other.getWeektimeSpan() == null : this.getWeektimeSpan().equals(other.getWeektimeSpan()))
            && (this.getMaxRise() == null ? other.getMaxRise() == null : this.getMaxRise().equals(other.getMaxRise()))
            && (this.getMaxFall() == null ? other.getMaxFall() == null : this.getMaxFall().equals(other.getMaxFall()))
            && (this.getAvgRange() == null ? other.getAvgRange() == null : this.getAvgRange().equals(other.getAvgRange()))
            && (this.getLatelyNum() == null ? other.getLatelyNum() == null : this.getLatelyNum().equals(other.getLatelyNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_returnprofit_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReportId() == null) ? 0 : getReportId().hashCode());
        result = prime * result + ((getWeektimeSpan() == null) ? 0 : getWeektimeSpan().hashCode());
        result = prime * result + ((getMaxRise() == null) ? 0 : getMaxRise().hashCode());
        result = prime * result + ((getMaxFall() == null) ? 0 : getMaxFall().hashCode());
        result = prime * result + ((getAvgRange() == null) ? 0 : getAvgRange().hashCode());
        result = prime * result + ((getLatelyNum() == null) ? 0 : getLatelyNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_returnprofit_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reportId=").append(reportId);
        sb.append(", weektimeSpan=").append(weektimeSpan);
        sb.append(", maxRise=").append(maxRise);
        sb.append(", maxFall=").append(maxFall);
        sb.append(", avgRange=").append(avgRange);
        sb.append(", latelyNum=").append(latelyNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}