package com.example.demo.model.fund;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PerformanceReportHalfyearsTempBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_halfyears_temp.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_halfyears_temp.report_id
     *
     * @mbggenerated
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_halfyears_temp.profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal profitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance_report_halfyears_temp.month_time
     *
     * @mbggenerated
     */
    private Date monthTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance_report_halfyears_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_halfyears_temp.id
     *
     * @return the value of performance_report_halfyears_temp.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_halfyears_temp.id
     *
     * @param id the value for performance_report_halfyears_temp.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_halfyears_temp.report_id
     *
     * @return the value of performance_report_halfyears_temp.report_id
     *
     * @mbggenerated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_halfyears_temp.report_id
     *
     * @param reportId the value for performance_report_halfyears_temp.report_id
     *
     * @mbggenerated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_halfyears_temp.profit_rate
     *
     * @return the value of performance_report_halfyears_temp.profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_halfyears_temp.profit_rate
     *
     * @param profitRate the value for performance_report_halfyears_temp.profit_rate
     *
     * @mbggenerated
     */
    public void setProfitRate(BigDecimal profitRate) {
        this.profitRate = profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance_report_halfyears_temp.month_time
     *
     * @return the value of performance_report_halfyears_temp.month_time
     *
     * @mbggenerated
     */
    public Date getMonthTime() {
        return monthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance_report_halfyears_temp.month_time
     *
     * @param monthTime the value for performance_report_halfyears_temp.month_time
     *
     * @mbggenerated
     */
    public void setMonthTime(Date monthTime) {
        this.monthTime = monthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_halfyears_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PerformanceReportHalfyearsTempBean other = (PerformanceReportHalfyearsTempBean) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReportId() == null ? other.getReportId() == null : this.getReportId().equals(other.getReportId()))
            && (this.getProfitRate() == null ? other.getProfitRate() == null : this.getProfitRate().equals(other.getProfitRate()))
            && (this.getMonthTime() == null ? other.getMonthTime() == null : this.getMonthTime().equals(other.getMonthTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_halfyears_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReportId() == null) ? 0 : getReportId().hashCode());
        result = prime * result + ((getProfitRate() == null) ? 0 : getProfitRate().hashCode());
        result = prime * result + ((getMonthTime() == null) ? 0 : getMonthTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_report_halfyears_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reportId=").append(reportId);
        sb.append(", profitRate=").append(profitRate);
        sb.append(", monthTime=").append(monthTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}